### ISSUE TITLE
Waveform and the music position de-synchronization after making several jumps

### ISSUE THREAD

**Issue by Soukyuu** [cboxdoerfer/ddb_waveform_seekbar#9] opened 2016-01-12 21:07 UTC
I can't really provide a reliable way to reproduce it, but jumping back and forth using waveform seekbar will eventually cause the music and the corresponding waveform to de-synchronize. For example, a quiet part of the music is played about 3-5 seconds before the corresponding low part in the waveform is reached. Once it has de-synchronized, the only way to make it synchronize again is to restart the track.

I don't know if it's relevant in any way, but I'm using the ffmpeg plugin (TAK audio) and pulse output.

**Comment by cboxdoerfer** [comment] 2016-01-12 21:45
Thx, nice catch. Can you try if this also happens with the default seekbar and with other decoders? And do the tracks which trigger that bug have a certain length (e.g. particularly short or long) or does it happen with any track?

**Comment by Soukyuu** [comment] 2016-01-14 20:23
Happens with the default seekbar too, and seemingly only with ffmpeg/tak. Looks like either ffmpeg or the ddb's plugin is sometimes unable to correctly seek to the correct position. The track length doesn't seem to matter, I tested a 2:14 and a 5:25 track, each in .tak and .mpc, both .tak tracks have about 2-3 seconds of desync, .mpc is robust.

**Comment by cboxdoerfer** [comment] 2016-04-25 18:11
Issue wasn't caused by waveform plugin. Closing that issue.

**Closed by cboxdoerfer** 2016-04-25 18:11 UTC
